name 'chef-linux-base-recipe'
maintainer 'HashiCorp'
maintainer_email 'hello@hashicorp.com'
license 'Apache-2.0'
description 'Installs/Configures chef-linux-base-recipe'
version '0.2.0'
chef_version '>= 18.0'

issues_url 'https://github.com/mtharpe/chef-linux-base-recipe/issues'
source_url 'https://github.com/mtharpe/chef-linux-base-recipe'

supports 'ubuntu', '>= 22.04'
supports 'debian', '>= 12.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'almalinux', '>= 8.0'

depends 'yum-epel', '~> 5.0'
depends 'vim', '~> 4.0'
depends 'os-hardening', '~> 5.0'
depends 'ssh-hardening', '~> 4.0'
